O:=\
    $(O) \
    $(DIR_LIB)/std/arm/memcmp.o \
    $(DIR_LIB)/std/arm/memcpy.o \
    $(DIR_LIB)/std/arm/memmove.o \
    $(DIR_LIB)/std/arm/memset.o \
    $(DIR_LIB)/std/arm/setjmp.o \
    $(DIR_LIB)/std/arm/strcmp.o \
    $(DIR_LIB)/std/arm/strncmp.o \
    $(DIR_LIB)/std/arm/gcc/__aeabi_idiv.c \
    $(DIR_LIB)/std/arm/gcc/__aeabi_idivmod.s \
    $(DIR_LIB)/std/arm/gcc/__aeabi_uidiv.c \
    $(DIR_LIB)/std/arm/gcc/__aeabi_uidivmod.s \
    $(DIR_LIB)/std/arm/gcc/__clzsi2.c \
    $(DIR_LIB)/std/arm/gcc/__divsi3.c \
    $(DIR_LIB)/std/arm/gcc/__modsi3.c \
    $(DIR_LIB)/std/arm/gcc/__udivmodsi4.c \
    $(DIR_LIB)/std/arm/gcc/__udivsi3.c \
    $(DIR_LIB)/std/arm/gcc/__umodsi3.c \
