struct task *scheduler_findactive();
struct task *scheduler_findinactive();
unsigned int scheduler_getactiveid();
void scheduler_attachactive(struct list *mailboxes);
void scheduler_detachactive(struct list *mailboxes);
void scheduler_detachlist(struct list *mailboxes);
unsigned int scheduler_readactive(unsigned int size, unsigned int count, void *buffer);
unsigned int scheduler_sendid(unsigned int id, unsigned int size, unsigned int count, void *buffer);
void scheduler_sendlist(struct list *mailboxes, unsigned int size, unsigned int count, void *buffer);
void scheduler_use(struct task *task);
void scheduler_unuse(struct task *task);
void scheduler_registertask(struct task *task);
void scheduler_unregistertask(struct task *task);
void scheduler_setup();
