unsigned int fsp_auth(char *path);
unsigned int fsp_link(unsigned int target, unsigned int id);
unsigned int fsp_list(unsigned int target, unsigned int id, unsigned int offset, struct record *records, unsigned int nrecords);
unsigned int fsp_read(unsigned int target, unsigned int id, void *buffer, unsigned int count, unsigned int offset);
unsigned int fsp_read_full(unsigned int target, unsigned int id, void *buffer, unsigned int count, unsigned int offset);
unsigned int fsp_read_all(unsigned int target, unsigned int id, void *buffer, unsigned int count, unsigned int offset);
unsigned int fsp_stat(unsigned int target, unsigned int id, struct record *record);
unsigned int fsp_unlink(unsigned int target, unsigned int id);
unsigned int fsp_walk(unsigned int target, unsigned int parent, char *path);
unsigned int fsp_write(unsigned int target, unsigned int id, void *buffer, unsigned int count, unsigned int offset);
unsigned int fsp_write_all(unsigned int target, unsigned int id, void *buffer, unsigned int count, unsigned int offset);
unsigned int fsp_spawn(char *path);
unsigned int fsp_spawn_relative(char *path, char *parent);
void fsp_bind(void);
