include $(DIR_SRC)/modules/arp/rules.mk
include $(DIR_SRC)/modules/audio/rules.mk
include $(DIR_SRC)/modules/base/rules.mk
include $(DIR_SRC)/modules/block/rules.mk
include $(DIR_SRC)/modules/clock/rules.mk
include $(DIR_SRC)/modules/con/rules.mk
include $(DIR_SRC)/modules/console/rules.mk
include $(DIR_SRC)/modules/ethernet/rules.mk
include $(DIR_SRC)/modules/event/rules.mk
include $(DIR_SRC)/modules/icmp/rules.mk
include $(DIR_SRC)/modules/ipv4/rules.mk
include $(DIR_SRC)/modules/ipv6/rules.mk
include $(DIR_SRC)/modules/keyboard/rules.mk
include $(DIR_SRC)/modules/log/rules.mk
include $(DIR_SRC)/modules/mouse/rules.mk
include $(DIR_SRC)/modules/mtwist/rules.mk
include $(DIR_SRC)/modules/null/rules.mk
include $(DIR_SRC)/modules/part/rules.mk
include $(DIR_SRC)/modules/pipe/rules.mk
include $(DIR_SRC)/modules/system/rules.mk
include $(DIR_SRC)/modules/timer/rules.mk
include $(DIR_SRC)/modules/udp/rules.mk
include $(DIR_SRC)/modules/video/rules.mk
include $(DIR_SRC)/modules/arch/$(ARCH)/rules.mk
