INIT_BIN:=$(PACKAGES_BINS_PATH)/init/init
INIT_OBJ:=$(PACKAGES_BINS_PATH)/init/init.o
INIT_CONF:=$(PACKAGES_BINS_PATH)/init/init.slang $(PACKAGES_BINS_PATH)/init/base.slang $(PACKAGES_BINS_PATH)/init/user.slang
INITMOD_BIN:=$(PACKAGES_BINS_PATH)/init/initmod
INITMOD_OBJ:=$(PACKAGES_BINS_PATH)/init/initmod.o
INITMOD_CONF:=$(PACKAGES_BINS_PATH)/init/initmod.conf
INITFS_BIN:=$(PACKAGES_BINS_PATH)/init/initfs
INITFS_OBJ:=$(PACKAGES_BINS_PATH)/init/initfs.o
INITFS_CONF:=$(PACKAGES_BINS_PATH)/init/initfs.conf

$(INIT_BIN): $(INIT_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

$(INITMOD_BIN): $(INITMOD_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

$(INITFS_BIN): $(INITFS_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

PACKAGES+=$(INIT_BIN) $(INITMOD_BIN) $(INITFS_BIN)
PACKAGES_OBJECTS+=$(INIT_OBJ) $(INITMOD_OBJ) $(INITFS_OBJ)
PACKAGES_CONFIGS+=$(INIT_CONF) $(INITMOD_CONF) $(INITFS_CONF)
