KEYMAPSE_BIN:=$(PACKAGES_BINS_PATH)/keymap/keymapse
KEYMAPSE_OBJ:=$(PACKAGES_BINS_PATH)/keymap/keymapse.o
KEYMAPUS_BIN:=$(PACKAGES_BINS_PATH)/keymap/keymapus
KEYMAPUS_OBJ:=$(PACKAGES_BINS_PATH)/keymap/keymapus.o

$(KEYMAPSE_BIN): $(KEYMAPSE_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

$(KEYMAPUS_BIN): $(KEYMAPUS_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

PACKAGES+=$(KEYMAPSE_BIN) $(KEYMAPUS_BIN)
PACKAGES_OBJECTS+=$(KEYMAPSE_OBJ) $(KEYMAPUS_OBJ)
