MOD:=$(MODULES_ARCH_PATH)/fpu/fpu.ko
OBJ:=$(MODULES_ARCH_PATH)/fpu/main.o $(MODULES_ARCH_PATH)/fpu/fpu.o

$(MOD): $(OBJ) $(LIBFUDGE)
	$(LD) $(LDFLAGS) -o $@ $^

MODULES+=$(MOD)
MODULES_OBJECTS+=$(OBJ)
