unsigned int file_walk(unsigned int id, char *path);
unsigned int file_walkfrom(unsigned int id, unsigned int root, char *path);
unsigned int file_duplicate(unsigned int id, unsigned int root);
unsigned int file_open(unsigned int id);
unsigned int file_close(unsigned int id);
unsigned int file_read(unsigned int id, void *buffer, unsigned int count);
unsigned int file_readall(unsigned int id, void *buffer, unsigned int count);
unsigned int file_write(unsigned int id, void *buffer, unsigned int count);
unsigned int file_writeall(unsigned int id, void *buffer, unsigned int count);
unsigned int file_seekread(unsigned int id, void *buffer, unsigned int count, unsigned int offset);
unsigned int file_seekreadall(unsigned int id, void *buffer, unsigned int count, unsigned int offset);
unsigned int file_seekwrite(unsigned int id, void *buffer, unsigned int count, unsigned int offset);
unsigned int file_seekwriteall(unsigned int id, void *buffer, unsigned int count, unsigned int offset);
