unsigned int cstring_length(char *in);
unsigned int cstring_lengthzero(char *in);
void cstring_copy(char *out, char *in);
unsigned int cstring_match(char *in1, char *in2);
unsigned int cstring_isalpha(char c);
unsigned int cstring_isdigit(char c);
unsigned int cstring_toint(char c);
unsigned int cstring_readvalue(char *in, unsigned int count, unsigned int base);
unsigned int cstring_write(char *out, unsigned int count, char *in, unsigned int offset);
unsigned int cstring_writezero(char *out, unsigned int count, unsigned int offset);
unsigned int cstring_writevalue(char *out, unsigned int count, int value, unsigned int base, unsigned int padding, unsigned int offset);
unsigned int cstring_writefmt(void *out, unsigned int count, char *fmt, unsigned int nargs, void **args, unsigned int offset);
