#define FILE_L0                         0x00
#define FILE_L1                         0x01
#define FILE_L2                         0x02
#define FILE_L3                         0x03
#define FILE_L4                         0x04
#define FILE_L5                         0x05
#define FILE_L6                         0x06
#define FILE_L7                         0x07
#define FILE_L8                         0x08
#define FILE_L9                         0x09
#define FILE_LA                         0x0A
#define FILE_LB                         0x0B
#define FILE_LC                         0x0C
#define FILE_LD                         0x0D
#define FILE_PP                         0x0E
#define FILE_PW                         0x0F
#define FILE_G0                         0x10
#define FILE_G1                         0x11
#define FILE_G2                         0x12
#define FILE_G3                         0x13
#define FILE_G4                         0x14
#define FILE_G5                         0x15
#define FILE_G6                         0x16
#define FILE_G7                         0x17
#define FILE_G8                         0x18
#define FILE_G9                         0x19
#define FILE_GA                         0x1A
#define FILE_GB                         0x1B
#define FILE_GC                         0x1C
#define FILE_GD                         0x1D
#define FILE_GE                         0x1E
#define FILE_GF                         0x1F
