#define P9P_TVERSION                    100
#define P9P_RVERSION                    101
#define P9P_TAUTH                       102
#define P9P_RAUTH                       103
#define P9P_TATTACH                     104
#define P9P_RATTACH                     105
#define P9P_TERROR                      106
#define P9P_RERROR                      107
#define P9P_TFLUSH                      108
#define P9P_RFLUSH                      109
#define P9P_TWALK                       110
#define P9P_RWALK                       111
#define P9P_TOPEN                       112
#define P9P_ROPEN                       113
#define P9P_TCREATE                     114
#define P9P_RCREATE                     115
#define P9P_TREAD                       116
#define P9P_RREAD                       117
#define P9P_TWRITE                      118
#define P9P_RWRITE                      119
#define P9P_TCLUNK                      120
#define P9P_RCLUNK                      121
#define P9P_TREMOVE                     122
#define P9P_RREMOVE                     123
#define P9P_TSTAT                       124
#define P9P_RSTAT                       125
#define P9P_TWSTAT                      126
#define P9P_RWSTAT                      127
