include packages/base/complete/rules.mk
include packages/base/echo/rules.mk
include packages/base/hello/rules.mk
include packages/base/help/rules.mk
include packages/base/initm/rules.mk
include packages/base/inits/rules.mk
include packages/base/load/rules.mk
include packages/base/ls/rules.mk
include packages/base/motd/rules.mk
include packages/base/reboot/rules.mk
include packages/base/shell/rules.mk
include packages/base/slang/rules.mk
include packages/base/unload/rules.mk
