include $(DIR_SRC)/modules/arch/x86/64bit/rules.mk
include $(DIR_SRC)/modules/arch/x86/acpi/rules.mk
include $(DIR_SRC)/modules/arch/x86/ahci/rules.mk
include $(DIR_SRC)/modules/arch/x86/apic/rules.mk
include $(DIR_SRC)/modules/arch/x86/ata/rules.mk
include $(DIR_SRC)/modules/arch/x86/atapi/rules.mk
include $(DIR_SRC)/modules/arch/x86/bga/rules.mk
include $(DIR_SRC)/modules/arch/x86/cpuid/rules.mk
include $(DIR_SRC)/modules/arch/x86/fpu/rules.mk
include $(DIR_SRC)/modules/arch/x86/i915/rules.mk
include $(DIR_SRC)/modules/arch/x86/ide/rules.mk
include $(DIR_SRC)/modules/arch/x86/io/rules.mk
include $(DIR_SRC)/modules/arch/x86/msr/rules.mk
include $(DIR_SRC)/modules/arch/x86/nvme/rules.mk
include $(DIR_SRC)/modules/arch/x86/pat/rules.mk
include $(DIR_SRC)/modules/arch/x86/pci/rules.mk
include $(DIR_SRC)/modules/arch/x86/pic/rules.mk
include $(DIR_SRC)/modules/arch/x86/pit/rules.mk
include $(DIR_SRC)/modules/arch/x86/platform/rules.mk
include $(DIR_SRC)/modules/arch/x86/ps2/rules.mk
include $(DIR_SRC)/modules/arch/x86/rtc/rules.mk
include $(DIR_SRC)/modules/arch/x86/rtl8139/rules.mk
include $(DIR_SRC)/modules/arch/x86/smp/rules.mk
ifeq ($(TARGET),i386-unknown-elf)
include $(DIR_SRC)/modules/arch/x86/syse/rules.mk
endif
include $(DIR_SRC)/modules/arch/x86/uart/rules.mk
include $(DIR_SRC)/modules/arch/x86/usb/rules.mk
include $(DIR_SRC)/modules/arch/x86/vbe/rules.mk
include $(DIR_SRC)/modules/arch/x86/vga/rules.mk
include $(DIR_SRC)/modules/arch/x86/virtio/rules.mk
