#define FUDGE_DI                        0x01
#define FUDGE_DO                        0x02
#define FUDGE_DC                        0x03
#define FUDGE_D0                        0x04
#define FUDGE_D1                        0x05
#define FUDGE_D2                        0x06
#define FUDGE_D3                        0x07
#define FUDGE_D4                        0x08
#define FUDGE_D5                        0x09
#define FUDGE_D6                        0x0A
#define FUDGE_D7                        0x0B
#define FUDGE_D8                        0x0C
#define FUDGE_D9                        0x0D
#define FUDGE_DW                        0x0E
#define FUDGE_DR                        0x0F
#define FUDGE_BSIZE                     0x1000
