COUNTB_BIN:=$(PACKAGES_BINS_PATH)/count/countb
COUNTB_OBJ:=$(PACKAGES_BINS_PATH)/count/countb.o
COUNTL_BIN:=$(PACKAGES_BINS_PATH)/count/countl
COUNTL_OBJ:=$(PACKAGES_BINS_PATH)/count/countl.o

$(COUNTB_BIN): $(COUNTB_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

$(COUNTL_BIN): $(COUNTL_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

PACKAGES+=$(COUNTB_BIN) $(COUNTL_BIN)
PACKAGES_OBJECTS+=$(COUNTB_OBJ) $(COUNTL_OBJ)
