include $(DIR_LIB)/abi/rules.mk
include $(DIR_LIB)/cpio/rules.mk
include $(DIR_LIB)/elf/rules.mk
include $(DIR_LIB)/event/rules.mk
include $(DIR_LIB)/fudge/rules.mk
include $(DIR_LIB)/keymap/rules.mk
include $(DIR_LIB)/math/rules.mk
include $(DIR_LIB)/mboot/rules.mk
include $(DIR_LIB)/md5/rules.mk
include $(DIR_LIB)/pcf/rules.mk
include $(DIR_LIB)/sha/rules.mk
include $(DIR_LIB)/tar/rules.mk
include $(DIR_LIB)/utf8/rules.mk
include $(DIR_LIB)/widget/rules.mk
