MOD:=$(MODULES_ARCH_PATH)/msr/msr.ko
OBJ:=$(MODULES_ARCH_PATH)/msr/main.o $(MODULES_ARCH_PATH)/msr/msr.o

$(MOD): $(OBJ) $(LIBFUDGE)
	$(LD) $(LDFLAGS) -o $@ $^

MODULES+=$(MOD)
MODULES_OBJECTS+=$(OBJ)
