#define PCI_BUS                         0x0002
#define PCI_CLASS_LEGACY                0x00
#define PCI_CLASS_STORAGE               0x01
#define PCI_CLASS_NETWORK               0x02
#define PCI_CLASS_DISPLAY               0x03
#define PCI_CLASS_MEDIA                 0x04
#define PCI_CLASS_MEMORY                0x05
#define PCI_CLASS_BRIDGE                0x06
#define PCI_CLASS_SIMPLE                0x07
#define PCI_CLASS_PERIPHERAL            0x08
#define PCI_CLASS_INPUT                 0x09
#define PCI_CLASS_DOCK                  0x0A
#define PCI_CLASS_PROCESSOR             0x0B
#define PCI_CLASS_SERIAL                0x0C
#define PCI_CLASS_WIRELESS              0x0D
#define PCI_CLASS_IO                    0x0E
#define PCI_CLASS_SATELLITE             0x0F
#define PCI_CLASS_CRYPT                 0x10
#define PCI_CLASS_SIGNAL                0x11
#define PCI_CLASS_OTHER                 0xFF
#define PCI_CLASS_LEGACY_NONVGA         0x00
#define PCI_CLASS_LEGACY_VGA            0x01
#define PCI_CLASS_STORAGE_SCSI          0x00
#define PCI_CLASS_STORAGE_IDE           0x01
#define PCI_CLASS_STORAGE_FLOPPY        0x02
#define PCI_CLASS_STORAGE_IPI           0x03
#define PCI_CLASS_STORAGE_RAID          0x04
#define PCI_CLASS_STORAGE_ATA           0x05
#define PCI_CLASS_STORAGE_SATA          0x06
#define PCI_CLASS_STORAGE_SAS           0x07
#define PCI_CLASS_STORAGE_NVME          0x08
#define PCI_CLASS_STORAGE_OTHER         0x80
#define PCI_CLASS_NETWORK_ETHERNET      0x00
#define PCI_CLASS_NETWORK_TOKENRING     0x01
#define PCI_CLASS_NETWORK_FDDI          0x02
#define PCI_CLASS_NETWORK_ATM           0x03
#define PCI_CLASS_NETWORK_ISDN          0x04
#define PCI_CLASS_NETWORK_WORLDFIP      0x05
#define PCI_CLASS_NETWORK_PICMG         0x06
#define PCI_CLASS_NETWORK_INFINIBAND    0x07
#define PCI_CLASS_NETWORK_FABRIC        0x08
#define PCI_CLASS_NETWORK_OTHER         0x80
#define PCI_CLASS_DISPLAY_VGA           0x00
#define PCI_CLASS_DISPLAY_XGA           0x01
#define PCI_CLASS_DISPLAY_3D            0x02
#define PCI_CLASS_DISPLAY_OTHER         0x80
#define PCI_CLASS_MEDIA_VIDEO           0x00
#define PCI_CLASS_MEDIA_AUDIO           0x01
#define PCI_CLASS_MEDIA_TELE            0x02
#define PCI_CLASS_MEDIA_OTHER           0x80
#define PCI_CLASS_MEMORY_RAM            0x00
#define PCI_CLASS_MEMORY_FLASH          0x01
#define PCI_CLASS_MEMORY_OTHER          0x80
#define PCI_CLASS_BRIDGE_HOST           0x00
#define PCI_CLASS_BRIDGE_ISA            0x01
#define PCI_CLASS_BRIDGE_EISA           0x02
#define PCI_CLASS_BRIDGE_MCA            0x03
#define PCI_CLASS_BRIDGE_PCI            0x04
#define PCI_CLASS_BRIDGE_PCMCIA         0x05
#define PCI_CLASS_BRIDGE_NUBUS          0x06
#define PCI_CLASS_BRIDGE_CARDBUS        0x07
#define PCI_CLASS_BRIDGE_RACEWAY        0x08
#define PCI_CLASS_BRIDGE_PCISEMI        0x09
#define PCI_CLASS_BRIDGE_INFINIBAND     0x0A
#define PCI_CLASS_BRIDGE_OTHER          0x80
#define PCI_CLASS_SIMPLE_SERIAL         0x00
#define PCI_CLASS_SIMPLE_PARALLEL       0x01
#define PCI_CLASS_SIMPLE_MULTIPORT      0x02
#define PCI_CLASS_SIMPLE_MODEM          0x03
#define PCI_CLASS_SIMPLE_GPIB           0x04
#define PCI_CLASS_SIMPLE_SMART          0x05
#define PCI_CLASS_SIMPLE_OTHER          0x80
#define PCI_CLASS_PERIPHERAL_PIC        0x00
#define PCI_CLASS_PERIPHERAL_DMA        0x01
#define PCI_CLASS_PERIPHERAL_TIMER      0x02
#define PCI_CLASS_PERIPHERAL_RTC        0x03
#define PCI_CLASS_PERIPHERAL_PCI        0x04
#define PCI_CLASS_PERIPHERAL_SD         0x05
#define PCI_CLASS_PERIPHERAL_IOMMU      0x06
#define PCI_CLASS_PERIPHERAL_OTHER      0x80
#define PCI_CLASS_INPUT_KEYBOARD        0x00
#define PCI_CLASS_INPUT_DIGITIZER       0x01
#define PCI_CLASS_INPUT_MOUSE           0x02
#define PCI_CLASS_INPUT_SCANNER         0x03
#define PCI_CLASS_INPUT_GAMEPORT        0x04
#define PCI_CLASS_INPUT_OTHER           0x80
#define PCI_CLASS_DOCK_GENERIC          0x01
#define PCI_CLASS_DOCK_OTHER            0x80
#define PCI_CLASS_PROCESSOR_386         0x00
#define PCI_CLASS_PROCESSOR_486         0x01
#define PCI_CLASS_PROCESSOR_PENTIUM     0x02
#define PCI_CLASS_PROCESSOR_ALPHA       0x10
#define PCI_CLASS_PROCESSOR_POWERPC     0x20
#define PCI_CLASS_PROCESSOR_MIPS        0x30
#define PCI_CLASS_PROCESSOR_COPROCESSOR 0x40
#define PCI_CLASS_SERIAL_FIREWIRE       0x00
#define PCI_CLASS_SERIAL_ACCESS         0x01
#define PCI_CLASS_SERIAL_SSA            0x02
#define PCI_CLASS_SERIAL_USB            0x03
#define PCI_CLASS_SERIAL_FIBRE          0x04
#define PCI_CLASS_SERIAL_SMBUS          0x05
#define PCI_CLASS_SERIAL_INFINIBAND     0x06
#define PCI_CLASS_SERIAL_IPMI           0x07
#define PCI_CLASS_SERIAL_SERCOS         0x08
#define PCI_CLASS_SERIAL_CANBUS         0x09
#define PCI_CLASS_WIRELESS_IRDA         0x00
#define PCI_CLASS_WIRELESS_IR           0x01
#define PCI_CLASS_WIRELESS_RF           0x10
#define PCI_CLASS_WIRELESS_BLUETOOTH    0x11
#define PCI_CLASS_WIRELESS_BROADBAND    0x12
#define PCI_CLASS_WIRELESS_80211A       0x20
#define PCI_CLASS_WIRELESS_80211B       0x21
#define PCI_CLASS_WIRELESS_OTHER        0x80
#define PCI_CLASS_IO_GENERIC            0x00
#define PCI_CLASS_SATELLITE_TV          0x01
#define PCI_CLASS_SATELLITE_AUDIO       0x02
#define PCI_CLASS_SATELLITE_VOICE       0x03
#define PCI_CLASS_SATELLITE_DATA        0x04
#define PCI_CLASS_CRYPT_NETWORK         0x00
#define PCI_CLASS_CRYPT_ENTERTAINMENT   0x01
#define PCI_CLASS_CRYPT_OTHER           0x80
#define PCI_CLASS_SIGNAL_DPIO           0x00
#define PCI_CLASS_SIGNAL_PERF           0x01
#define PCI_CLASS_SIGNAL_SYNC           0x10
#define PCI_CLASS_SIGNAL_MANAGEMENT     0x20
#define PCI_CLASS_SIGNAL_OTHER          0x80
#define PCI_CONFIG_VENDOR               0x00
#define PCI_CONFIG_DEVICE               0x02
#define PCI_CONFIG_COMMAND              0x04
#define PCI_CONFIG_STATUS               0x06
#define PCI_CONFIG_REVISION             0x08
#define PCI_CONFIG_INTERFACE            0x09
#define PCI_CONFIG_SUBCLASS             0x0A
#define PCI_CONFIG_CLASS                0x0B
#define PCI_CONFIG_CACHE                0x0C
#define PCI_CONFIG_TIMER                0x0D
#define PCI_CONFIG_HEADER               0x0E
#define PCI_CONFIG_BIST                 0x0F
#define PCI_CONFIG_BAR0                 0x10
#define PCI_CONFIG_BAR1                 0x14
#define PCI_CONFIG_BAR2                 0x18
#define PCI_CONFIG_BAR3                 0x1C
#define PCI_CONFIG_BAR4                 0x20
#define PCI_CONFIG_BAR5                 0x24
#define PCI_CONFIG_CARDBUS              0x28
#define PCI_CONFIG_SUBVENDOR            0x2C
#define PCI_CONFIG_SUBSYSTEM            0x2E
#define PCI_CONFIG_EXPANSION            0x30
#define PCI_CONFIG_CAPABILITIES         0x34
#define PCI_CONFIG_LINE                 0x3C
#define PCI_CONFIG_PIN                  0x3D
#define PCI_CONFIG_GRANT                0x3E
#define PCI_CONFIG_LATENCY              0x3F

unsigned int pci_ind(unsigned int id, unsigned short offset);
unsigned short pci_inw(unsigned int id, unsigned short offset);
unsigned char pci_inb(unsigned int id, unsigned short offset);
void pci_outd(unsigned int id, unsigned short offset, unsigned int value);
void pci_outw(unsigned int id, unsigned short offset, unsigned short value);
void pci_outb(unsigned int id, unsigned short offset, unsigned char value);
void pci_setmaster(unsigned int id);
unsigned short pci_getirq(unsigned int id);
