MODLOAD_BIN:=$(PACKAGES_PATH)/mod/modload
MODLOAD_OBJ:=$(PACKAGES_PATH)/mod/modload.o
MODUNLOAD_BIN:=$(PACKAGES_PATH)/mod/modunload
MODUNLOAD_OBJ:=$(PACKAGES_PATH)/mod/modunload.o

$(MODLOAD_BIN): $(MODLOAD_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

$(MODUNLOAD_BIN): $(MODUNLOAD_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

PACKAGES+=$(MODLOAD_BIN) $(MODUNLOAD_BIN)
PACKAGES_OBJECTS+=$(MODLOAD_OBJ) $(MODUNLOAD_OBJ)
