NAMED_BIN:=$(PACKAGES_PATH)/name/named
NAMED_OBJ:=$(PACKAGES_PATH)/name/named.o
NAMEF_BIN:=$(PACKAGES_PATH)/name/namef
NAMEF_OBJ:=$(PACKAGES_PATH)/name/namef.o

$(NAMED_BIN): $(NAMED_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

$(NAMEF_BIN): $(NAMEF_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

PACKAGES+=$(NAMED_BIN) $(NAMEF_BIN)
PACKAGES_OBJECTS+=$(NAMED_OBJ) $(NAMEF_OBJ)
