#define CONFIG_FRAME_WIDTH                  4
#define CONFIG_FRAME_HEIGHT                 4
#define CONFIG_BUTTON_PADDING_WIDTH         (CONFIG_FRAME_WIDTH + 24)
#define CONFIG_BUTTON_PADDING_HEIGHT        (CONFIG_FRAME_HEIGHT + 16)
#define CONFIG_CHOICE_PADDING_WIDTH         (CONFIG_FRAME_WIDTH + 24)
#define CONFIG_CHOICE_PADDING_HEIGHT        (CONFIG_FRAME_HEIGHT + 16)
#define CONFIG_LAYOUT_PADDING_WIDTH         8
#define CONFIG_LAYOUT_PADDING_HEIGHT        8
#define CONFIG_LISTBOX_PADDING_WIDTH        0
#define CONFIG_LISTBOX_PADDING_HEIGHT       0
#define CONFIG_SELECT_PADDING_WIDTH         (CONFIG_FRAME_WIDTH + 24)
#define CONFIG_SELECT_PADDING_HEIGHT        (CONFIG_FRAME_HEIGHT + 16)
#define CONFIG_TEXTBOX_PADDING_WIDTH        16
#define CONFIG_TEXTBOX_PADDING_HEIGHT       16
#define CONFIG_TEXTBUTTON_PADDING_WIDTH     (CONFIG_FRAME_WIDTH + 24)
#define CONFIG_TEXTBUTTON_PADDING_HEIGHT    (CONFIG_FRAME_HEIGHT + 16)
#define CONFIG_WINDOW_BORDER_WIDTH          16
#define CONFIG_WINDOW_BORDER_HEIGHT         16
#define CONFIG_WINDOW_BUTTON_WIDTH          32
#define CONFIG_WINDOW_BUTTON_HEIGHT         32
#define CONFIG_WINDOW_MIN_WIDTH             320
#define CONFIG_WINDOW_MIN_HEIGHT            200
