$(PACKAGES_PATH)/%.o: CFLAGS+=-I$(LIBS_PATH)/fudge

USERLIBS:=$(LIBABI) $(LIBFUDGE)

include $(PACKAGES_BINS_PATH)/cat/rules.mk
include $(PACKAGES_BINS_PATH)/cconv/rules.mk
include $(PACKAGES_BINS_PATH)/col/rules.mk
include $(PACKAGES_BINS_PATH)/complete/rules.mk
include $(PACKAGES_BINS_PATH)/count/rules.mk
include $(PACKAGES_BINS_PATH)/cpio/rules.mk
include $(PACKAGES_BINS_PATH)/crc/rules.mk
include $(PACKAGES_BINS_PATH)/date/rules.mk
include $(PACKAGES_BINS_PATH)/dep/rules.mk
include $(PACKAGES_BINS_PATH)/dump/rules.mk
include $(PACKAGES_BINS_PATH)/echo/rules.mk
include $(PACKAGES_BINS_PATH)/head/rules.mk
include $(PACKAGES_BINS_PATH)/hello/rules.mk
include $(PACKAGES_BINS_PATH)/help/rules.mk
include $(PACKAGES_BINS_PATH)/init/rules.mk
include $(PACKAGES_BINS_PATH)/keymap/rules.mk
include $(PACKAGES_BINS_PATH)/ls/rules.mk
include $(PACKAGES_BINS_PATH)/mandelbrot/rules.mk
include $(PACKAGES_BINS_PATH)/md5/rules.mk
include $(PACKAGES_BINS_PATH)/mod/rules.mk
include $(PACKAGES_BINS_PATH)/motd/rules.mk
include $(PACKAGES_BINS_PATH)/mount/rules.mk
include $(PACKAGES_BINS_PATH)/name/rules.mk
include $(PACKAGES_BINS_PATH)/nl/rules.mk
include $(PACKAGES_BINS_PATH)/pcx/rules.mk
include $(PACKAGES_BINS_PATH)/reboot/rules.mk
include $(PACKAGES_BINS_PATH)/sha1/rules.mk
include $(PACKAGES_BINS_PATH)/share/rules.mk
include $(PACKAGES_BINS_PATH)/shell/rules.mk
include $(PACKAGES_BINS_PATH)/slang/rules.mk
include $(PACKAGES_BINS_PATH)/sleep/rules.mk
