PCXDATA_BIN:=$(PACKAGES_BINS_PATH)/pcx/pcxdata
PCXDATA_OBJ:=$(PACKAGES_BINS_PATH)/pcx/pcxdata.o
PCXCMAP_BIN:=$(PACKAGES_BINS_PATH)/pcx/pcxcmap
PCXCMAP_OBJ:=$(PACKAGES_BINS_PATH)/pcx/pcxcmap.o

$(PCXDATA_BIN): $(PCXDATA_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

$(PCXCMAP_BIN): $(PCXCMAP_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

PACKAGES+=$(PCXDATA_BIN) $(PCXCMAP_BIN)
PACKAGES_OBJECTS+=$(PCXDATA_OBJ) $(PCXCMAP_OBJ)
