HEADB_BIN:=$(PACKAGES_PATH)/head/headb
HEADB_OBJ:=$(PACKAGES_PATH)/head/headb.o
HEADL_BIN:=$(PACKAGES_PATH)/head/headl
HEADL_OBJ:=$(PACKAGES_PATH)/head/headl.o

$(HEADB_BIN): $(HEADB_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

$(HEADL_BIN): $(HEADL_OBJ) $(USERLIBS)
	$(LD) $(LDFLAGS) -o $@ $^

PACKAGES+=$(HEADB_BIN) $(HEADL_BIN)
PACKAGES_OBJECTS+=$(HEADB_OBJ) $(HEADL_OBJ)
