include $(DIR_SRC)/abi/rules.mk
include $(DIR_SRC)/elf/rules.mk
include $(DIR_SRC)/format/rules.mk
include $(DIR_SRC)/fudge/rules.mk
include $(DIR_SRC)/kernel/rules.mk
include $(DIR_SRC)/mandelbrot/rules.mk
include $(DIR_SRC)/mboot/rules.mk
include $(DIR_SRC)/md5/rules.mk
include $(DIR_SRC)/modules/rules.mk
include $(DIR_SRC)/sha/rules.mk
include $(DIR_SRC)/utils/rules.mk
include $(DIR_SRC)/wm/rules.mk
include $(DIR_SRC)/pcx/rules.mk
