LIBLOADER:=$(LIBS_PATH)/x86/mboot/libmboot.a
LIBLOADER_OBJ:=$(LIBS_PATH)/x86/mboot/main.o $(LIBS_PATH)/x86/mboot/mboot.o

$(LIBLOADER): $(LIBLOADER_OBJ)
	$(AR) $(ARFLAGS) $@ $^

LIBS+=$(LIBLOADER)
LIBS_OBJECTS+=$(LIBLOADER_OBJ)
