include modules/arch/x86/acpi/rules.mk
include modules/arch/x86/apic/rules.mk
include modules/arch/x86/ata/rules.mk
include modules/arch/x86/atapi/rules.mk
include modules/arch/x86/bga/rules.mk
include modules/arch/x86/cpuid/rules.mk
include modules/arch/x86/fpu/rules.mk
include modules/arch/x86/i915/rules.mk
include modules/arch/x86/ide/rules.mk
include modules/arch/x86/io/rules.mk
include modules/arch/x86/msr/rules.mk
include modules/arch/x86/pci/rules.mk
include modules/arch/x86/pic/rules.mk
include modules/arch/x86/pit/rules.mk
include modules/arch/x86/platform/rules.mk
include modules/arch/x86/ps2/rules.mk
include modules/arch/x86/rtc/rules.mk
include modules/arch/x86/rtl8139/rules.mk
include modules/arch/x86/smp/rules.mk
include modules/arch/x86/uart/rules.mk
include modules/arch/x86/vga/rules.mk
