include $(MODULES_ARCH_PATH)/acpi/rules.mk
include $(MODULES_ARCH_PATH)/apic/rules.mk
include $(MODULES_ARCH_PATH)/ata/rules.mk
include $(MODULES_ARCH_PATH)/atapi/rules.mk
include $(MODULES_ARCH_PATH)/bga/rules.mk
include $(MODULES_ARCH_PATH)/cirrus/rules.mk
include $(MODULES_ARCH_PATH)/cpuid/rules.mk
include $(MODULES_ARCH_PATH)/fpu/rules.mk
include $(MODULES_ARCH_PATH)/i915/rules.mk
include $(MODULES_ARCH_PATH)/ide/rules.mk
include $(MODULES_ARCH_PATH)/io/rules.mk
include $(MODULES_ARCH_PATH)/msr/rules.mk
include $(MODULES_ARCH_PATH)/pci/rules.mk
include $(MODULES_ARCH_PATH)/pic/rules.mk
include $(MODULES_ARCH_PATH)/pit/rules.mk
include $(MODULES_ARCH_PATH)/platform/rules.mk
include $(MODULES_ARCH_PATH)/ps2/rules.mk
include $(MODULES_ARCH_PATH)/rtc/rules.mk
include $(MODULES_ARCH_PATH)/rtl8139/rules.mk
include $(MODULES_ARCH_PATH)/smp/rules.mk
include $(MODULES_ARCH_PATH)/uart/rules.mk
include $(MODULES_ARCH_PATH)/vga/rules.mk
