struct list_item *pool_next(struct list_item *current);
struct list_item *pool_nextin(struct list_item *current, struct widget *parent);
struct widget *pool_getwidgetbyid(unsigned int source, char *id);
void pool_bump(struct widget *widget);
struct widget *pool_create(unsigned int source, unsigned int type, char *id, char *in);
char *pool_getstring(unsigned int index);
unsigned int pool_getcstringlength(unsigned int index);
unsigned int pool_savedata(unsigned int count, void *data);
unsigned int pool_savestring(char *string);
unsigned int pool_freestring(unsigned int index);
unsigned int pool_replacestring(unsigned int index, char *string);
void pool_setup(void);
