struct list_item *pool_next(struct list_item *current);
struct list_item *pool_nextin(struct list_item *current, struct widget *parent);
struct widget *pool_getwidgetbyid(unsigned int source, char *id);
void pool_bump(struct widget *widget);
struct widget *pool_create(unsigned int source, unsigned int type, char *id, char *in);
char *pool_getstring(unsigned int index);
unsigned int pool_getcstringlength(unsigned int index);
unsigned int pool_getcstringlengthz(unsigned int index);
unsigned int pool_savedata(unsigned int count, void *data);
unsigned int pool_savecstring(char *cstring);
unsigned int pool_freedata(unsigned int index);
unsigned int pool_replacecstring(unsigned int index, char *cstring);
void pool_setup(void);
